name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: sanity
        run: |
          ls 
          ls ${{ github.workspace }}

      - name: setup
        run: |
          haxe --version
          haxelib install tink_testrunner
          haxelib install tink_unittest
          haxelib install checkstyle
          haxelib install tink_cli

      - name: checkstyle
        run: |
          haxelib run checkstyle -s src
          haxelib run checkstyle -s tests

      - name: tests
        run: haxe tests.hxml
